<? /* $Id: edit.phtml,v 1.1 2002/10/12 08:56:30 mose Exp $
Copyright (C) 2002, Makina Corpus, http://makinacorpus.org
This file is a component of Localis <http://localis.makina-corpus.org>
Created by mose@makina-corpus.org and mastre@makina-corpus.org
Maintained by Makina Corpus <localis@makina-corpus.org>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
USA.

This script is freely adapted from PHP Explorer 0.7
Author: Marcelo L. Mottalli <mottalli@sinectis.com.ar>
Homepage: http://phpexplorer.sourceforge.net
*/

// quick and dirty authentication scheme.
// quick solution : set those variables
// and change the if (false) in if (true)
$vlogin = "";
$vpassd = "";
// fix that asap
if (false) {
  if (!isset($PHP_AUTH_USER)) {
    header("WWW-Authenticate: Basic realm=\"Localis Admin\"");
    header("HTTP/1.0 401 Unauthorized");
    echo "Go away, intruder ! or I blast YOU.\n";
    exit;
  } else {
    if (($PHP_AUTH_USER == $vlogin) && ($PHP_AUTH_PW == $vpassd)) {

    } else {
      echo "Bad try. Restart your computer and try again.\n";
      exit;
    }
  }
} else {
	echo "Please fix the authentication in edit.phtml.";
	exit;
}

include "../inc/parseconf.php";
$conf = parseconf('../etc/localis.conf');
foreach ($conf as $k=>$v) ${"conf_$k"} = $v;

$where[templates] = $conf_tpl_path;
$where[images] = $conf_root_path."/images";
$where[conf] = $conf_root_path."/etc";
$where[maps] = $conf_root_path."/maps";
$where[data] = $conf_root_path."/maps/data";
$where[fonts] = $conf_root_path."/maps/fonts";

$wheres = array_keys($where);

if ((!$wh) or (!in_array($wh,$wheres))) {
	$wh = 'templates';
}

function nav_where($wh) {
	global $wheres;
	foreach ($wheres as $w) {
		if ($w == $wh) {
			$back[] = "<b>$w</b>";
		} else {
			$back[] = "<a href=$PHP_SELF?wh=$w>$w</a>";
		}
	}
	return implode(" . ",$back);
}

	$rootdir = $where[$wh];
	if (substr($dir,0,strlen($rootdir)) != $rootdir) {
		$dir = $rootdir;
	}

   //************************************************************************//
   //* PHP Explorer 0.7                     Codename: "mustard"             *//
   //* Author: Marcelo L. Mottalli <mottalli@sinectis.com.ar>               *//
   //* Homepage: http://phpexplorer.sourceforge.net/                        *//
   //************************************************************************//

////////////////////////////////   USEFUL VARIABLES   /////////////////////////////

   $associations = array(   	
      "gif" =>  array(   "function" => "viewGIF",   "icon" => "icons/gif.gif"     ),
      "jpg" =>  array(   "function" => "viewJPEG",  "icon" => "icons/jpeg.gif"    ),
      "jpeg" => array(   "function" => "viewJPEG",  "icon" => "icons/jpeg.gif"    ),
      "png" =>  array(   "function" => "viewPNG",   "icon" => "icons/png.gif"    ),
      "shp" =>  array(   "function" => "viewSHP",   "icon" => "icons/file.gif"   ),
      "dbf" =>  array(   "function" => "viewDBF",   "icon" => "icons/file.gif"   ),
      "php" =>  array(   "function" => "viewPHP",   "icon" => ""                  )
   );

////////////////////////////////     CONSTANTS     ////////////////////////////////

   $OS_UNIX 					= true;			// UNIX or Windows?

   $PHP_EXPLORER_VERSION   = "v0.7";
   $BACKGROUND_COLOR       = "#ffffff";
   $FONT_COLOR             = "#000000";
   $TABLE_BORDER_COLOR     = "#000000";
   $TABLE_BACKGROUND_COLOR = "#ffffff";
   $TABLE2_BACKGROUND_COLOR= "#eeeeee";
   $TABLE_FONT_COLOR       = "#000000";
   $COLOR_PRIVATE          = "#ffbb99";
   $COLOR_PUBLIC           = "#cceeff";
   $LINK_COLOR             = "#0000ff";
   $LINK_HOVER_COLOR       = "#ff0000";
   $DEFAULT_FONT           = "Verdana";
	$show_icons = true;

   $default_directory = $rootdir;   
   
   if (!isset($dir) || $dir == "") $dir = $default_directory;
   $dir = stripslashes($dir);
   $dir = str_replace("\\", "/", $dir);         // Windows compatibility

   if ($OS_UNIX) {
   	$USERNAME = "www-data";
   }

   $fileInfo = new fileInfo;        // This will hold a file's information all over the script   
 
///////////////////////////     BEGIN OF THE SCRIPT     ///////////////////////////   

   switch ($action) {
      case "view":
      	viewFile($dir);
      	break;
      case "edit":
         printHTMLHeader();
      	showFile($dir, 1);
      	break;
      case "download":
         viewFileHeader($dir, "Content-type: application/octet-stream");
         break;
      case "delete":
         printHTMLHeader();
         deleteFile($dir);
				 $dir = dirname($dir);
         $show_directory = true;
         $show_footer = true;
         break;
      case "upload":
         printHTMLHeader();
         uploadFile();
         $show_directory = true;
         $show_footer = true;
         break;
      case "save":
         printHTMLHeader();
      	saveFile($dir);
         $show_directory = true;
         $show_footer = true;
         break;
      case "rename":
         printHTMLHeader();
         renameFile($dir, $rename_to);
         $dir = dirname($dir);
         break;
      case "showreferences" :
         showReferences();
         break;
      default:
         printHTMLHeader();
         $show_directory = true;
         $show_footer = true;
         break;
   };
   
   if (isset($show_directory) && $show_directory = true) showDirectory($dir);
   if (isset($show_footer) && $show_footer = true) printHTMLFooter();
   
   exit;

   //************************************************************************
   //* Class fileInfo: stores a file's information
   //************************************************************************

   class fileInfo {
      var $name, $path, $fullname, $isDir, $lastmod, $owner,
      $perms, $size, $isLink, $linkTo, $extension, $wh;

      function permissions($mode) {
         $perms  = ($mode & 00400) ? "r" : "-";
         $perms .= ($mode & 00200) ? "w" : "-";
         $perms .= ($mode & 00100) ? "x" : "-";
         $perms .= ($mode & 00040) ? "r" : "-";
         $perms .= ($mode & 00020) ? "w" : "-";
         $perms .= ($mode & 00010) ? "x" : "-";
         $perms .= ($mode & 00004) ? "r" : "-";
         $perms .= ($mode & 00002) ? "w" : "-";
         $perms .= ($mode & 00001) ? "x" : "-";
         return $perms;
      }

      function getInfo($file) {                 // Stores a file's information in the class variables
         $this->name = basename($file);
         $this->path = dirname($file);
         $this->fullname = $file;
         $this->isDir = is_dir($file);
         $this->lastmod = date("m/d/y, H:i", filemtime($file));
         $this->owner = fileowner($file);
         $this->perms = $this->permissions(fileperms($file));
         $this->size = filesize($file);
         $this->isLink = is_link($file);
         if ($this->isLink) $this->linkTo = readlink($file);
         $buffer = explode(".", $this->fullname);
         $this->extension = array_pop($buffer); 
      }
   };


///////////////////////////////     HTML STYLE     ///////////////////////////////

   function printHTMLHeader() {
      global $PHP_SELF, $FONT_COLOR, $TABLE_FONT_COLOR, $LINK_COLOR, $LINK_HOVER_COLOR;
      global $BACKGROUND_COLOR, $DEFAULT_FONT, $wh;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Localis : PHP Explorer</title>
<style type="text/css">
<!--
   .body { font-family: "<?= $DEFAULT_FONT ?>"; font-size: 13 ; color: "<?= $FONT_COLOR ?>" }
   body, table, div, tr, td {font-family: "<?= $DEFAULT_FONT ?>"; font-size: 13; color: "<?= $TABLE_FONT_COLOR ?>" }
   a {text-decoration: none; color: "<?= $LINK_COLOR ?>" }
   a:hover {text-decoration: none; color: "<?= $LINK_HOVER_COLOR ?>" }
-->
</style>
</head>
<body class="body" bgcolor="<?= $BACKGROUND_COLOR; ?>">
<?
	} // End of printHTMLHeader() 

   function printHTMLFooter() {
      global $PHP_SELF, $PHP_EXPLORER_VERSION, $dir, $wh;
?>
<p>
<? if ((is_dir($dir) && (fileperms($dir) & 00200))):  // is $dir world-writeable? 
?>
   <table border="0">
   <tr><td>
      <form enctype="multipart/form-data" action="<?= "$PHP_SELF?wh=$wh&dir=$dir&action=upload" ?>" method="post">
         <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
         <input name="userfile" type="file">
         <input type="submit" value="Upload file">
      </form>
   </td>
   </tr>
   </table>
<? endif; ?>
   <div align="right"><font size="-1"><b>PHP Explorer</b> <?= $PHP_EXPLORER_VERSION; ?></font></div>
</body>
</html>
<? 
   }  // End of printHTMLFooter ()
   
///////////////////////////     DIRECTORY FUNCTIONS     ///////////////////////////
   
   //************************************************************************
   //* Stores a directory's files and directories on 
   //* the arrays $files and $directories respectively.
   //************************************************************************

   function readDirectory($directory) {
      global $files, $directories;

      $files = array();
      $directories = array();
      $a = 0;
      $b = 0;
    
      $dirHandler = @opendir($directory) 
         or throw_error("Could not open directory <i>$directory</i>", true);
      
      while ($file = readdir($dirHandler)) {
         if (substr($file,0,1) != ".") {
   
            $fullName = $directory.($directory == "/" ? "" : "/").$file;
   
            if (is_dir($fullName)) $directories[$a++] = $fullName;
            else $files[$b++] = $fullName;
         }
      }
      sort($directories);                    // We want them to be displayed alphabetically
      sort($files);
   };

   //************************************************************************
   //* Shows a directory's information
   //************************************************************************

   function showInfoDirectory($directory) {
      global $PHP_SELF, $TABLE_BORDER_COLOR, $TABLE2_BACKGROUND_COLOR, $OS_UNIX, $USERNAME, $wh;

      echo "<p><div align=\"right\"><table cellpadding=3 cellspacing=1 width=\"100%\" border=\"0\" bgcolor=\"$TABLE_BORDER_COLOR\">\n";
      echo "<tr><td bgcolor=\"$TABLE2_BACKGROUND_COLOR\" align=\"left\" width=\"90%\">";
   
      $dirs = split("/", $directory);
      print "<b><font size=\"-1\">Directory <a href=\"$PHP_SELF?wh=$wh&dir=/\">/</a>";
      $upper_directory = "";
   
      for ($i = 1; $i < (sizeof($dirs)); $i++) {
         print "<a href=\"$PHP_SELF?dir=";
   
         for ($a = 1; $a <= $i; $a++)
            echo "/$dirs[$a]";
   
         echo "\">$dirs[$i]</a>";
   
         if ($i < ((sizeof($dirs) - 1))) $upper_directory .= "/$dirs[$i]";
         if ($directory != "/") echo "/";
      }
   
      if ($upper_directory == "") $upper_directory = "/";

      echo "</font></b>\n";
      echo "</td>\n";
      echo "<td align=\"center\" width=\"10%\" bgcolor=\"$TABLE2_BACKGROUND_COLOR\"><b><a href=\"$PHP_SELF?wh=$wh&dir=$upper_directory\">Up</a></b></td>\n";
      echo "</tr></table></div>";

      echo "</small></div>\n";
   };

   //************************************************************************
   //* Shows directory's content
   //************************************************************************
   
   function showDirectory($directory) {
      global $files, $directories, $fileInfo, $PHP_SELF, $TABLE_BORDER_COLOR, $TABLE_BACKGROUND_COLOR;
      global $show_icons, $TABLE2_BACKGROUND_COLOR, $wh;

      echo "<p><b><font face='Arial' size='+2'>PHP Explorer for <a href=../index.php>Localis</a></font></b> &nbsp;&nbsp;";
			echo nav_where($wh);

      readDirectory($directory);
      #showInfoDirectory($directory);
?>
      <p><table cellpadding=3 cellspacing=1 width="100%" border="0" bgcolor="<?= $TABLE_BORDER_COLOR; ?>">
         <tr bgcolor="#dddddd">
            <? if ($show_icons): ?>
            <td width="16" align="center" bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>">&nbsp;</td>
            <? endif; ?>
            <td align="center"><b><small>Nom</small></b></td>
            <td align="center"><b><small>Taille</small></b></td>
            <td align="center"><b><small>Derniere Modif</small></b></td>
            <td align="center"><b><small>Permissions</small></b></td>
            <td align="center"><b><small>Actions</small></b></td>
         </tr>
<?
      for ($i = 0; $i < sizeof($directories); $i++) {
         $fileInfo->getInfo($directories[$i]);
         showFileInfo($fileInfo);
      }

      for ($i = 0; $i < sizeof($files); $i++) {
         $fileInfo->getInfo($files[$i]);
         showFileInfo($fileInfo);
      }
?>
      </table>
      <p><table cellpadding=3 cellspacing=1 width="100%" border="0" bgcolor="<?= $TABLE_BORDER_COLOR; ?>">
      <tr bgcolor="<?= $TABLE2_BACKGROUND_COLOR ?>"><td align="center">
      <b>
      <a href="<?= $PHP_SELF ?>?action=showreferences" target="_blank">Help</a>
      </b>
      </td></tr>
      </table>      
<?
   };

   //************************************************************************
   //* Creates a directory
   //************************************************************************
   
   function createDirectory($directory) {
      global $PHP_SELF, $dir_from;

      $old_umask = umask(0);

      if (strrpos($directory, "/") === false) $dirname="$dir_from/$directory";   // Relative path?
      else $dirname = $directory;

      if (!@mkdir($dirname, 0777))
         throw_error("Could not create directory $dirname");

      umask($old_umask);
   }
   

/////////////////////////////     FILE FUNCTIONS     //////////////////////////////

   //************************************************************************
   //* Shows a file and/or directory info and makes the corresponding links
   //************************************************************************

   function showFileInfo($fileInfo) {
      global $PHP_SELF, $wh, $associations, $TABLE_BACKGROUND_COLOR, $COLOR_PUBLIC, $COLOR_PRIVATE;
      global $show_icons;

      echo "\n<tr bgcolor=\"$TABLE_BACKGROUND_COLOR\" align=\"center\">";
      
      if (isset($show_icons) && $show_icons == true) {
         echo "<td>";      

         if ($fileInfo->isDir) echo "<img src=\"/icons/dir.gif\" width=11 height=11 alt=\"\">";
         elseif ($associations["$fileInfo->extension"]["icon"] != "")
            echo "<img src=\"".$associations[$fileInfo->extension]["icon"]."\" alt=\"\">";
         else echo "<img src=\"icons/generic.gif\" alt=\"\">";

         echo "</td>";
      }
      
      echo "<td align=\"left\""; 

      if ($fileInfo->perms[1] == "w") echo " bgcolor=\"$COLOR_PUBLIC\"";
      if ($fileInfo->perms[1] == "-") echo " bgcolor=\"$COLOR_PRIVATE\"";

      echo ">";

      if ($fileInfo->isLink) {
         echo $fileInfo->name." -> ";
         $fileInfo->fullname = $fileInfo->linkTo;
         $fileInfo->name = $fileInfo->linkTo;
      }

      if ($fileInfo->isDir && $fileInfo->perms[6] != "-") {       // Make directory link if not private
         echo "<b><a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname\" ";
         echo ">$fileInfo->name</a></b>";
      }
      else echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=edit\">$fileInfo->name</a>";

      echo "</td>";
      echo "<td>$fileInfo->size</td>";
      echo "<td>$fileInfo->lastmod</td>";
      echo "<td>$fileInfo->perms</td>";
      echo "<td>";
      
      if (!$fileInfo->isDir) {
         if ($fileInfo->perms[6] == 'r') {
            echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=view\"> V</a>";
            echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=download\"> D</a>";
         }

         if ($fileInfo->perms[7] == 'w') {
            echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=edit\"> E</a>";
         }
      }

      if ($fileInfo->perms[7] == 'w') {
         echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=rename\"> R</a>";
         echo "<a href=\"$PHP_SELF?wh=$wh&dir=$fileInfo->fullname&amp;action=delete\"> X</a>";
      }

      echo "</tr>";
      flush();
   };

   //************************************************************************
   //* Decides which function use to show a file
   //************************************************************************

   function viewFile($file) {
      global $associations, $fileInfo;
      $fileInfo->getInfo($file);

      if (!$associations[$fileInfo->extension] 
          || $associations[$fileInfo->extension]["function"] == "") showFile($file);
      else $associations[$fileInfo->extension]["function"]($file);
   };
	
	//************************************************************************
	//* Shows a file in the default form. If the variable $editing is different 
   //* to 0, it edits the file
	//************************************************************************

   function showFile($file, $editing = 0) {
      global $PHP_SELF, $dir, $wh;
      $handlerFile = @fopen($file, "r") or throw_error("Could not open file $file", true);
      
			echo "<a href=$PHP_SELF?wh=$wh>Localis : Editeur</a> ";
      if ($editing) echo "<h3><b>Edition du fichier $file</b></h3><hr>";
      else echo "<h3><b>Fichier $file</b></h3><hr>";
      
      echo "<form";
      if ($editing) 
         echo " action=\"$PHP_SELF?wh=$wh&action=save&dir=$file\" method=\"post\"";
      echo ">";
      
      $buffer = fread($handlerFile, filesize($file));
      $buffer = str_replace("&", "&amp;", $buffer);
      $buffer = str_replace("<", "&lt;", $buffer);
      $buffer = str_replace(">", "&gt;", $buffer);
      
      echo "<textarea wrap=\"off\" cols=\"96\" rows=\"40\" name=\"text\">$buffer</textarea>";
			echo "<input type=hidden name=wh value=$wh>";
      if ($editing) echo "<p><input type=\"submit\" name=\"Submit\" value=\"Enregistrer\">\n</form>";
      echo "</form>";
      fclose($handlerFile);
   };
	
   //************************************************************************
   //* Saves a changed file
   //************************************************************************

   function saveFile($file) {
      global $dir, $text;

      $handlerFile = @fopen($file, "w") or throw_error("Could not open file ".basename($file)." for writing", true);
      $text = stripslashes($text);

      fwrite($handlerFile, $text, strlen($text)) or throw_error("Could not write to file", true);
      fclose($handlerFile);

      echo "Changes have been saved in ".basename($file)."<hr>";
      $dir = dirname($file);
   };

   //************************************************************************
   //* Uploads a file to the server
   //************************************************************************
   
   function uploadFile() {
      global $HTTP_POST_FILES, $dir, $wh;
      
      @copy($HTTP_POST_FILES["userfile"][tmp_name], $dir."/".$HTTP_POST_FILES["userfile"][name]) 
      or throw_error("Could not upload file".$HTTP_POST_FILES["userfile"][tmp_name], true);

			chmod($dir."/".$HTTP_POST_FILES["userfile"][name],0664);
      
      echo "File ".$HTTP_POST_FILES["userfile"][name]." succesfully uploaded.";
      unlink($userfile);
   };
   
   //************************************************************************
   //* Deletes a file, asking for confirmation first
   //************************************************************************
   
   function deleteFile($file) {
      global $confirm, $PHP_SELF, $conf, $wh;

      if ($confirm != TRUE) die("<a href=$PHP_SELF?wh=$wh>$conf[editor_name]</a><br><br><a href=\"$PHP_SELF?wh=$wh&dir=$file&action=delete&confirm=1\">Confirm deletion of $file</a>");
      else {
         if (is_dir($file)) {
            if (!@rmdir($file)) throw_error("Could not delete directory $file");
            else echo "Directory $file succesfully deleted<br>";
         }
         else {
            if (!@unlink($file)) throw_error("Could not delete file $file");
            else echo "$file succesfully deleted<br>";            
         }
      }
   };

   //************************************************************************
   //* Renames a file
   //************************************************************************

   function renameFile($file, $rename_to = "") {
      global $PHP_SELF, $show_directory, $show_footer, $wh;
      if (!isset($rename_to) || $rename_to == "") {
         echo "<form action=\"$PHP_SELF\">\n";
         echo "<input type=\"hidden\" name=\"action\" value=\"rename\">\n";
         echo "<input type=\"hidden\" name=\"dir\" value=\"$file\">\n";
         echo "<input type=\"hidden\" name=\"wh\" value=\"$wh\">\n";
         echo "<p>Rename/move file <b>$file</b> (relative to ".getcwd().")<br>\n";
         echo "To: <input type=\"text\" name=\"rename_to\" value=\"".basename($file)."\"><br><br>\n";
         echo "<input type=\"submit\" value=\"Rename\">\n";
         echo "</form>\n";
      }
      else {
         chdir(dirname($file));
         if (!@rename($file, $rename_to)) throw_error("Could not rename $file to $rename_to");
         else echo "$file renamed/moved succesfully.<br>\n";
         $show_directory = true;
         $show_footer = true;
      }
   }
   
   //************************************************************************
   //* Echoes a file to the output sending previously an HTML header.
   //* Used to download files of certain MIME type and to display images. 
   //* Can also be used for plugins.
   //************************************************************************

   function viewFileHeader($file, $header) {
      header($header);
      header("Content-Length: ".filesize($file));
      readfile($file);
   };

   //************************************************************************
   //* Functions for viewing associated files (AKA "plugins")
   //************************************************************************
	
   function viewGIF($file) {
      viewFileHeader($file, "Content-type: image/gif");
   };

   function viewPNG($file) {
      viewFileHeader($file, "Content-type: image/png");
   };

   function viewJPEG($file) {
      viewFileHeader($file, "Content-type: image/jpeg");
   };
   
   function viewPHP($file) {
      show_source($file);
   }
   
   // Include any additional plugin file in here using the function
   // require("plugin_file")

//////////////////////////////     MISC FUNCTIONS     /////////////////////////////

   function throw_error($text, $end = false) {     // Shows an error message
      global $php_errormsg;

      echo "<b>Error:</b> $text";
      if (isset($php_errormsg)) echo ". <b>Last PHP error:</b> <i>$php_errormsg</i>";
      echo "<br><br>\n";

      if ($end == true) die();
   }
   
   function showReferences() {
      global $TABLE_BORDER_COLOR, $TABLE_BACKGROUND_COLOR, $COLOR_PRIVATE, $COLOR_PUBLIC;
      printHTMLHeader();
?>
      <table cellpadding=3 cellspacing=1 border="0" bgcolor="<?= $TABLE_BORDER_COLOR; ?>">
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td colspan="2" align="center"><b>Légendes:</b></td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td>V</td><td>Visualiser un fichier</td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td>D</td><td>Télécharger un fichier</td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td>E</td><td>Editer un fichier (permissions 777 nécessaire)</td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td>X</td><td>Efface un fichier ou dossier (permissions 777 nécessaire)</td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td bgcolor="<?= $COLOR_PUBLIC ?>">&nbsp;</td><td>Accès public</td></tr>
      <tr bgcolor="<?= $TABLE_BACKGROUND_COLOR ?>"><td bgcolor="<?= $COLOR_PRIVATE ?>">&nbsp;</td><td>Accès privé</td></tr>
      </table>
<?
   }
?>
